# Change these first
owner: NetaMx # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/NetaMx/upptime/master/assets/Logo_Neta_Close.png
  name: NetaMX Upptime
  introTitle: "NetaMX Estado de Servicios"
  introMessage: NetaMX Estado de Servicios
  navbar:
    - title: Estado
      href: /
    - title: Llama a Soporte
      href: /
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
